eventos/mysite/eventos/urls.py
from django.urls import path

from . import views

app_name = 'eventos'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    # ex: /eventos/list
    path('list/', views.ListEvent.as_view(), name='list'),
    # ex: /eventos/register
    path('register/', views.registerEvent, name='register'),
    # ex: /eventos/5/
    path('<int:pk>/', views.DetailEvent.as_view(), name='detail'),

]

eventos/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('eventos/', include('eventos.urls')),
    path('admin/', admin.site.urls),
]

eventos/mysite/eventos/models.py
from django.utils import timezone
from django.db import models
from django_countries.fields import CountryField

# Create your models here.


class Country(models.Model):
    """
    Our Country models objects are created here and stored in the database
    as a table with the attributes mentioned below.
    """

    COUNTRY_CHOICES = (

        ('AR', 'Argentina'),
        ('AU', 'Australia'),
        ('AT', 'Austria'),
        ('BO', 'Bolivia'),
        ('BR', 'Brazil'),
        ('CA', 'Canada'),
        ('CL', 'Chile'),
        ('CN', 'China'),
        ('CO', 'Colombia'),
        ('IN', 'India'),
        ('ID', 'Indonesia'),
        ('MX', 'Mexico'),
        ('NL', 'Netherlands'),
        ('ZA', 'South Africa'),
        ('US', 'United States of America'),
        ('UY', 'Uruguay'),

    )
    country = models.CharField(
        max_length=2,
        choices=COUNTRY_CHOICES,
    )

    class Meta:
        ordering = ["country"]

    def __str__(self):
        return self.country


class Event(models.Model):
    """
    Our Event models objects are created here and stored in the database
    as a table with the attributes mentioned below.
    """

    event_description = models.CharField(max_length=200)
    event_date = models.DateField('Event date')
    event_time = models.TimeField('Event time')
    event_country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.event_description

eventos/mysite/eventos/forms.py
from django import forms
from .models import Event


class RegisterForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['event_description', 'event_date', 'event_time', 'event_country']

eventos/mysite/eventos/views.py
import pytz

from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from django.views import generic

from .models import Event, Country
from .forms import RegisterForm


def index(request):
    """
    Our index view function that allows to either list all events
    of register a new event.
    """
    return render(request, 'eventos/index.html')


def registerEvent(request):
    """
    Our view function to register an event in the database.
    """

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            event_description = form.cleaned_data['event_description']
            event_date = form.cleaned_data['event_date']
            event_time = form.cleaned_data['event_time']
            event_country = form.cleaned_data['event_country']
            print(event_description)
            print(event_date)
            print(event_country)

            Event.objects.create(event_description=event_description, event_date=event_date, event_time=event_time, event_country=event_country)

            return HttpResponseRedirect(reverse('eventos:list'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render(request, 'eventos/form.html', {'form': form})


class ListEvent(generic.ListView):
    """
    The view function to list all the events in the database.
    """
    template_name = 'eventos/list.html'
    context_object_name = 'event_list'

    def get_queryset(self):
        """Return all the events registered so far."""
        return Event.objects.all()


class DetailEvent(generic.DetailView):
    """
    The view function that show the detail of each event like the
    date, time and country.
    """
    model = Event
    template_name = 'eventos/detail.html'


def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')
    else:
        return render(request, 'template.html', {'timezones': pytz.common_timezones})

eventos/mysite/eventos/templates/eventos/detail.html
<table>
        <tr>
            <th>Event Name</th>
            <th>Host Country</th>
            <th>Date</th>
            <th>Time</th>
        </tr>

        <tr>
            <td style="text-align: center;"><a href="/eventos/{{ event.id }}/">{{ event.event_description }}</a></td>
            <td style="text-align: center;">{{ event.event_country }}</td>
            <td style="text-align: center;">{{ event.event_date }}</td>
            <td style="text-align: center;">{{ event.event_time }}</td>
        </tr>

    </table>


<br><br>
<h3><a href={% url 'eventos:list' %}>Return to all events.</a></h3>
<br><br>
<h3><a href={% url 'eventos:index' %}>Return to Home</a></h3>

eventos/mysite/eventos/templates/eventos/form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        <caption>REGISTER YOUR EVENT</caption>
        {{ form.as_table }}
    </table>

    <input type="submit" value="Register">
</form>


<br><br>
<h3><a href={% url 'eventos:list' %}>Return to all events</a></h3>
<h3><a href={% url 'eventos:index' %}>Return to Home</a></h3>

eventos/mysite/eventos/templates/eventos/index.html
<ul>
<li><h2><a href="{% url 'eventos:list' %}">List all Events</a></h2></li>
<li><h2><a href="{% url 'eventos:register' %}">Book an Event</a></h2></li>
</ul>   

eventos/mysite/eventos/templates/eventos/list.html
{% load tz %}

{% localtime on %}
    {{ value }}
{% endlocaltime %}

{% localtime off %}
    {{ value }}
{% endlocaltime %}

{% if event_list %}

    <table>
        <tr>
            <th>Event Name</th>
            <th>Host Country</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
    {% for event in event_list %}
        <tr>
            <td style="text-align: center;"><a href="/eventos/{{ event.id }}/">{{ event.event_description }}</a></td>
            <td style="text-align: center;">{{ event.event_country }}</td>
            <td style="text-align: center;">{{ event.event_date }}</td>
            <td style="text-align: center;">{{ event.event_time }}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <h3>No events are available.</h3>
{% endif %}


<h3><a href={% url 'eventos:index' %}>Return to Home</a></h3>

eventos/mysite/eventos/templates/eventos/template.html
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<form action="{% url 'set_timezone' %}" method="POST">
    {% csrf_token %}
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for tz in timezones %}
        <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set">
</form>